/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import DAO.FuncionarioDAO;
import Models.Funcionario;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author mateus
 */
public class interfaceFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form interfaceFuncionario
     */
    public interfaceFuncionario() {
        initComponents();
        DefaultTableModel modeloTabela = (DefaultTableModel) tabelaInformacoes.getModel();
        tabelaInformacoes.setRowSorter(new TableRowSorter(modeloTabela));

        readTabela();
    }

    public void readTabela() {
        DefaultTableModel modeloTabela = (DefaultTableModel) tabelaInformacoes.getModel();
        modeloTabela.setNumRows(0);
        FuncionarioDAO funcionarioDAO = new FuncionarioDAO();
        
        
        funcionarioDAO.listaFuncionario().forEach((f) -> {
            modeloTabela.addRow(new Object[]{
                f.getId(),
                f.getNome(),
                f.getCargo(),
                f.getSalario(),
                f.getSalarioLiquido()
            });
        });
    }

    public void readTabelaForNome(String nome) {
        DefaultTableModel modeloTabela = (DefaultTableModel) tabelaInformacoes.getModel();
        modeloTabela.setNumRows(0);
        FuncionarioDAO buscarFuncionarioDAO = new FuncionarioDAO();
        
        for (Funcionario f : buscarFuncionarioDAO.listaFuncionario(nome)) {
            modeloTabela.addRow(new Object[]{
                f.getId(),
                f.getNome(),
                f.getCargo(),
                f.getSalario(),
                f.getSalarioLiquido()
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textSalario = new javax.swing.JTextField();
        textCargo = new javax.swing.JTextField();
        textNome = new javax.swing.JTextField();
        bttnDeletar = new javax.swing.JButton();
        bttnCadastrar = new javax.swing.JButton();
        bttnAtualizar = new javax.swing.JButton();
        bttnAtualizar1 = new javax.swing.JButton();
        textBusca = new javax.swing.JTextField();
        bttnImposto = new javax.swing.JButton();
        bttnINSS = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaInformacoes = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel1.setText("Salário:");

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel2.setText("Nome:");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel3.setText("Cargo:");

        textSalario.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N

        textCargo.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        textCargo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCargoActionPerformed(evt);
            }
        });

        textNome.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        textNome.setToolTipText("");

        bttnDeletar.setText("Deletar");
        bttnDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnDeletarActionPerformed(evt);
            }
        });

        bttnCadastrar.setText("Cadastrar");
        bttnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnCadastrarActionPerformed(evt);
            }
        });

        bttnAtualizar.setText("Atualizar");
        bttnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAtualizarActionPerformed(evt);
            }
        });

        bttnAtualizar1.setText("Buscar");
        bttnAtualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttnAtualizar1ActionPerformed(evt);
            }
        });

        bttnImposto.setText("Imposto de Renda");

        bttnINSS.setText("INSS");

        tabelaInformacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Cargo", "Salário", "Salário Liquido"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true, true, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelaInformacoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaInformacoesMouseClicked(evt);
            }
        });
        tabelaInformacoes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tabelaInformacoesKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaInformacoes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(bttnImposto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(bttnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bttnDeletar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bttnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(bttnAtualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bttnINSS, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(textBusca))))
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textNome, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCargo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnImposto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bttnINSS, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(bttnAtualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(textBusca, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(bttnCadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bttnAtualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textCargoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCargoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCargoActionPerformed

    private void bttnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnCadastrarActionPerformed
        // TODO add your handling code here:
        Funcionario funcionario = new Funcionario();
        FuncionarioDAO saveFuncionario = new FuncionarioDAO();
        
        funcionario.setNome(textNome.getText());
        funcionario.setCargo(textCargo.getText());
        funcionario.setSalario(Float.parseFloat(textSalario.getText()));
        
        saveFuncionario.Create(funcionario);
        
        textNome.setText("");
        textCargo.setText("");
        textSalario.setText("");
        
        readTabela();
    }//GEN-LAST:event_bttnCadastrarActionPerformed

    private void tabelaInformacoesKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tabelaInformacoesKeyReleased
        // TODO add your handling code here:
        if (tabelaInformacoes.getSelectedRow() != -1) {
            textNome.setText(tabelaInformacoes.getValueAt(tabelaInformacoes.getSelectedRow(), 1).toString());
            textCargo.setText(tabelaInformacoes.getValueAt(tabelaInformacoes.getSelectedRow(), 2).toString());
            textSalario.setText(tabelaInformacoes.getValueAt(tabelaInformacoes.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_tabelaInformacoesKeyReleased

    private void bttnDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnDeletarActionPerformed
        // TODO add your handling code here:
        if (tabelaInformacoes.getSelectedRow() != -1) {
            Funcionario funcionario = new Funcionario();
            FuncionarioDAO deleteFuncionario = new FuncionarioDAO();
            
            funcionario.setId((int) tabelaInformacoes.getValueAt(tabelaInformacoes.getSelectedRow(), 0));
            
            deleteFuncionario.Delete(funcionario);
            
            textNome.setText("");
            textCargo.setText("");
            textSalario.setText("");
            
            readTabela();
        }
    }//GEN-LAST:event_bttnDeletarActionPerformed

    private void bttnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAtualizarActionPerformed
        // TODO add your handling code here:
        
        if (tabelaInformacoes.getSelectedRow() != -1) {
            Funcionario funcionario = new Funcionario();
            FuncionarioDAO updateFuncionario = new FuncionarioDAO();
            
            funcionario.setNome(textNome.getText());
            funcionario.setCargo(textCargo.getText());
            funcionario.setSalario(Float.parseFloat(textSalario.getText()));
            funcionario.setId((int)tabelaInformacoes.getValueAt(tabelaInformacoes.getSelectedRow(), 0));
            
            updateFuncionario.Update(funcionario);
            
            textNome.setText("");
            textCargo.setText("");
            textSalario.setText("");
            
            readTabela();
        }
    }//GEN-LAST:event_bttnAtualizarActionPerformed

    private void tabelaInformacoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaInformacoesMouseClicked
        // TODO add your handling code here:
        if (tabelaInformacoes.getSelectedRow() != -1) {
            textNome.setText(tabelaInformacoes.getValueAt(tabelaInformacoes.getSelectedRow(), 1).toString());
            textCargo.setText(tabelaInformacoes.getValueAt(tabelaInformacoes.getSelectedRow(), 2).toString());
            textSalario.setText(tabelaInformacoes.getValueAt(tabelaInformacoes.getSelectedRow(), 3).toString());
        }
    }//GEN-LAST:event_tabelaInformacoesMouseClicked

    private void bttnAtualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttnAtualizar1ActionPerformed
        // TODO add your handling code here:
        readTabelaForNome(textBusca.getText());
    }//GEN-LAST:event_bttnAtualizar1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfaceFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfaceFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfaceFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfaceFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfaceFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bttnAtualizar;
    private javax.swing.JButton bttnAtualizar1;
    private javax.swing.JButton bttnCadastrar;
    private javax.swing.JButton bttnDeletar;
    private javax.swing.JButton bttnINSS;
    private javax.swing.JButton bttnImposto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaInformacoes;
    private javax.swing.JTextField textBusca;
    private javax.swing.JTextField textCargo;
    private javax.swing.JTextField textNome;
    private javax.swing.JTextField textSalario;
    // End of variables declaration//GEN-END:variables
}
